function [modelout, clust_par_means, outputText, outputStats] = tsglm_run_clustperm_eeg(all_coefs, formula, cfg, modelout)
% =========================================================================
% Cluster-based permutation tests on participant-level EEG GLM coefficients.
%
% Each field in all_coefs represents one model coefficient:
%
%   all_coefs.<coefficient>{subject}.avg
%
% where avg has dimensions:
%
%   channels x time
%
% The test is a one-sample test against zero, implemented as a dependent-
% samples t-test between the observed coefficient maps and zero maps.
%
% INPUTS
% -------------------------------------------------------------------------
% all_coefs
%   Structure with one field per coefficient. Each field contains a cell
%   array of FieldTrip timelock structures, one per participant.
%
% formula
%   Model formula. Stored in modelout for reference.
%
% cfg
%   Configuration structure.
%
%   General options:
%       cfg.verbose
%       cfg.cut_short_clusters
%       cfg.minlength
%       cfg.cut_non_significant_clusters
%       cfg.subject_ids
%       cfg.fieldtrip_cfg
%
%   Important FieldTrip options:
%       cfg.fieldtrip_cfg.numrandomization
%       cfg.fieldtrip_cfg.clusteralpha
%       cfg.fieldtrip_cfg.alpha
%       cfg.fieldtrip_cfg.neighbours
%       cfg.fieldtrip_cfg.minnbchan
%
%   If neighbours is empty, clustering occurs only over adjacent time
%   samples within each channel. For spatiotemporal EEG clustering, provide
%   a neighbour structure created with ft_prepare_neighbours.
%
% modelout
%   Existing output structure. May be empty.
%
% OUTPUTS
% -------------------------------------------------------------------------
% modelout
%   Contains:
%       obs_clusters_sum
%       cluster_masks
%       fieldtrip_cfg
%       parameter_names
%       formula
%       alpha
%       n_subjects
%       n_channels
%       n_timepoints
%
% clust_par_means
%   Table containing each participant's mean coefficient estimate inside
%   each retained cluster's actual channel x time mask.
%
% outputText
%   Console output generated by ft_timelockstatistics for each coefficient.
%
% outputStats
%   FieldTrip stat structure for each coefficient. Each structure also has:
%       cluster_summary_all
%       cluster_summary
%
% =========================================================================

start_time = tic;


%% Set defaults ========================================================
if nargin < 4 || isempty(modelout);                         modelout = struct();                                end
if nargin < 3 || isempty(cfg);                              cfg = struct();                                     end
if nargin < 2;                                              formula = "";                                       end
if ~isstruct(all_coefs) || isempty(fieldnames(all_coefs));  error("all_coefs must be a nonempty structure.");   end
if ~isstruct(cfg);                                          error("cfg must be a structure.");                  end
if ~isstruct(modelout);                                     error("modelout must be a structure.");             end

verbose                         = get_or_default(cfg, 'verbose', true);
cut_short_clusters              = get_or_default(cfg, 'cut_short_clusters', false);
minlength                       = get_or_default(cfg, 'minlength', 0);
cut_non_significant_clusters    = get_or_default(cfg, 'cut_non_significant_clusters', true);
fieldtrip_cfg                   = get_or_default(cfg, 'fieldtrip_cfg', struct() );

if ~isscalar(minlength) || minlength < 0 || fix(minlength) ~= minlength
    error("cfg.minlength must be a nonnegative integer.");
end

% FieldTrip defaults 
fieldtrip_cfg.parameter         = get_or_default(fieldtrip_cfg, 'parameter', 'avg');
fieldtrip_cfg.method            = get_or_default(fieldtrip_cfg, "method", "montecarlo");
fieldtrip_cfg.statistic         = get_or_default(fieldtrip_cfg, "statistic", "depsamplesT");
fieldtrip_cfg.correctm          = get_or_default(fieldtrip_cfg, "correctm", "cluster");
fieldtrip_cfg.clusterstatistic  = get_or_default(fieldtrip_cfg, "clusterstatistic", "maxsum");
fieldtrip_cfg.numrandomization  = get_or_default(fieldtrip_cfg, "numrandomization", 1000);
fieldtrip_cfg.tail              = get_or_default(fieldtrip_cfg, "tail", 0);
fieldtrip_cfg.clustertail       = get_or_default(fieldtrip_cfg, "clustertail", 0);
fieldtrip_cfg.clusteralpha      = get_or_default(fieldtrip_cfg, "clusteralpha", 0.05);
fieldtrip_cfg.alpha             = get_or_default(fieldtrip_cfg, "alpha", 0.05);
fieldtrip_cfg.correcttail       = get_or_default(fieldtrip_cfg, "correcttail", "prob");
fieldtrip_cfg.neighbours        = get_or_default(fieldtrip_cfg, "neighbours", []);
fieldtrip_cfg.spmversion        = get_or_default(fieldtrip_cfg, "spmversion", "spm12");
fieldtrip_cfg.feedback          = get_or_default(fieldtrip_cfg, "feedback", "no");

% Subject and condition rows in the design matrix.
fieldtrip_cfg.uvar = 1;
fieldtrip_cfg.ivar = 2;

% If spatial neighbours are provided, require at least two neighbouring
% channels by default. Do not set minnbchan for temporal-only clustering
% unless the user explicitly supplied it.
if ~isempty(fieldtrip_cfg.neighbours) && ~isfield(fieldtrip_cfg, "minnbchan")
    fieldtrip_cfg.minnbchan = 2;
end


%% Check the data structure ==================================================

% get parameter names and number
par_names = fieldnames(all_coefs);
n_par     = numel(par_names);

% get one parameter for reference
first_parameter = all_coefs.(par_names{1});

% validate the paremter
if ~iscell(first_parameter) || isempty(first_parameter)
    error( ...
        "all_coefs.%s must be a nonempty cell array.", ...
        par_names{1} ...
    );
end

% number of subjects
n_subjs = numel(first_parameter);

% get one reference subject
reference = first_parameter{1};

validate_timelock_structure( ...
    reference, ...
    par_names{1}, ...
    1 ...
);

reference_labels = string(reference.label(:));  % electrodes labels
reference_time   = reference.time(:)';          % time vector
reference_size   = size(reference.avg);         % coefficient matrix size (should be n channel x time series length)

n_chans = reference_size(1); % number of channels
ts_len  = reference_size(2); % time series length

% validate the number of channels
if numel(reference_labels) ~= n_chans
    error( ...
        ["The number of channel labels (%d) does not match the number " ...
         "of rows in avg (%d)."], ...
        numel(reference_labels), ...
        n_chans ...
    );
end


if numel(reference_time) ~= ts_len
    error( ...
        ["The time-vector length (%d) does not match the number " ...
         "of columns in avg (%d)."], ...
        numel(reference_time), ...
        ts_len ...
    );
end


%% Subject identifiers ====================================================
% use default ids if they are not provided in the cfg structure
default_subject_ids = string((1:n_subjs)');

subject_ids = get_or_default(cfg, "subject_ids", default_subject_ids);
subject_ids = string(subject_ids(:));

% validate the ids
if numel(subject_ids) ~= n_subjs
    error( ...
        ["cfg.subject_ids contains %d identifiers, but all_coefs " ...
         "contains %d participants."], ...
        numel(subject_ids), ...
        n_subjs ...
    );
end


%% Validate every parameter and participant ===============================
for pp = 1 : n_par
    
    % get parameter name and estimates
    parameter_name = par_names{pp};
    subjdata       = all_coefs.(parameter_name);

    % validate the format of estimates
    if ~iscell(subjdata)
        error( ...
            "all_coefs.%s must be a cell array.", ...
            parameter_name ...
        );
    end
    
    % validate the number of estimtaes
    if numel(subjdata) ~= n_subjs
        error( ...
            ["Parameter %s contains %d participants, whereas the first " ...
             "parameter contains %d participants."], ...
            parameter_name, ...
            numel(subjdata), ...
            n_subjs ...
        );
    end

    % loop through participants
    for ii = 1 : n_subjs
        
        % validate subject's structure
        validate_timelock_structure( ...
            subjdata{ii}, ...
            parameter_name, ...
            ii ...
        );

        current_labels = string(subjdata{ii}.label(:)); % electrodes labels
        current_time   = subjdata{ii}.time(:)';         % time vector
        current_size   = size(subjdata{ii}.avg);        % coefficient matrix size
        
        % validate labels
        if ~isequal(current_labels, reference_labels)
            error( ...
                ["Channel labels or channel order differ for parameter " ...
                 "%s, participant %d."], ...
                parameter_name, ...
                ii ...
            );
        end
        
        % ensure coefficient matrix's size is the same across participants
        if ~isequal(current_size, reference_size)
            error( ...
                ["Coefficient dimensions differ for parameter %s, " ...
                 "participant %d. Expected %d x %d but found %d x %d."], ...
                parameter_name, ...
                ii, ...
                reference_size(1), ...
                reference_size(2), ...
                current_size(1), ...
                current_size(2) ...
            );
        end

        % ensure the time vector is the same across participants
        if numel(current_time) ~= numel(reference_time) || ...
                any(abs(current_time - reference_time) > 1e-12)

            error( ...
                ["Time axes differ for parameter %s, " ...
                 "participant %d."], ...
                parameter_name, ...
                ii ...
            );
        end

        if any(~isfinite(subjdata{ii}.avg), "all")
            error( ...
                ["Nonfinite coefficient estimates found for parameter " ...
                 "%s, participant %d."], ...
                parameter_name, ...
                ii ...
            );
        end
    end
end


%% FieldTrip design matrix =================================================

design = zeros(2, 2 * n_subjs);

design(1, :) = repmat(1:n_subjs, 1, 2);
design(2, :) = [
    ones(1, n_subjs), ...
    2 .* ones(1, n_subjs)
];

fieldtrip_cfg.design = design;


%% Preallocate outputs =====================================================

outputText  = cell(n_par, 1);
outputStats = cell(n_par, 1);

obs_clusters_sum = table();
clust_par_means   = table();

% For each coefficient, this contains the retained cluster masks in the same
% order as the coefficient-specific rows in obs_clusters_sum.
cluster_masks = cell(n_par, 1);


%% Run cluster-based permutation tests ====================================

if verbose
    fprintf( ...
        "Running cluster permutation tests for %d coefficients, %d participants, %d channels and %d time points.\n", ...
        n_par, ...
        n_subjs, ...
        n_chans, ...
        ts_len);

    if isempty(fieldtrip_cfg.neighbours)
        fprintf( ...
            "No spatial neighbours supplied: clusters will extend over time within channels, but not across channels.\n"...
        );
    else
        fprintf( ...
            "Spatial neighbours supplied: testing spatiotemporal clusters.\n" ...
        );
    end
end


for pp = 1:n_par

    parameter_name = par_names{pp};
    subjdata       = all_coefs.(parameter_name);

    if verbose
        fprintf( ...
            "%d/%d | %s\n", ...
            pp, ...
            n_par, ...
            parameter_name ...
        );
    end

    % Create participant-specific zero maps with the same FieldTrip metadata.
    zero_data = subjdata;

    for ii = 1:n_subjs
        zero_data{ii}.avg = zeros( ...
            size(subjdata{ii}.avg), ...
            "like", ...
            subjdata{ii}.avg ...
        );
    end

    % Run FieldTrip and capture its console output.
    try
        outputText{pp} = evalc( ...
            "stat = ft_timelockstatistics(fieldtrip_cfg, subjdata{:}, zero_data{:});" ...
        );
    catch ME
        error( ...
            "Cluster permutation failed for coefficient %s:\n%s", ...
            parameter_name, ...
            ME.message ...
        );
    end

    % Extract candidate positive and negative clusters.
    [pos_clusters, pos_masks] = extract_eeg_clusters( ...
        stat, ...
        "posclusters", ...
        "posclusterslabelmat", ...
        "positive" ...
    );

    [neg_clusters, neg_masks] = extract_eeg_clusters( ...
        stat, ...
        "negclusters", ...
        "negclusterslabelmat", ...
        "negative" ...
    );

    % Combine positive and negative clusters.
    if ~isempty(pos_clusters) && ~isempty(neg_clusters)

        all_clusters = [
            pos_clusters
            neg_clusters
        ];

        all_masks = [
            pos_masks
            neg_masks
        ];

    elseif ~isempty(pos_clusters)

        all_clusters = pos_clusters;
        all_masks    = pos_masks;

    elseif ~isempty(neg_clusters)

        all_clusters = neg_clusters;
        all_masks    = neg_masks;

    else

        all_clusters = table();
        all_masks    = cell(0, 1);
    end

    % Sort candidate clusters by onset time.
    if ~isempty(all_clusters)

        [all_clusters, sort_order] = sortrows( ...
            all_clusters, ...
            ["first_sample", "direction"] ...
        );

        all_masks = all_masks(sort_order);
    end

    % Preserve all candidate clusters in the FieldTrip output.
    stat.cluster_summary_all = all_clusters;

    % Retain clusters according to the requested criteria.
    clusters = all_clusters;
    masks    = all_masks;

    if ~isempty(clusters)

        keep_cluster = true(height(clusters), 1);

        if cut_short_clusters
            keep_cluster = keep_cluster & ...
                clusters.n_timepoints >= minlength;
        end

        if cut_non_significant_clusters
            keep_cluster = keep_cluster & ...
                clusters.prob <= fieldtrip_cfg.alpha;
        end

        clusters = clusters(keep_cluster, :);
        masks    = masks(keep_cluster);

        % Number retained clusters within this coefficient.
        clusters.clustern = (1:height(clusters))';

        % Add coefficient name.
        clusters.pred = repmat( ...
            string(parameter_name), ...
            height(clusters), ...
            1 ...
        );

        % Reorder key columns.
        clusters = movevars( ...
            clusters, ...
            ["pred", "clustern"], ...
            "Before", ...
            1 ...
        );
    end

    stat.cluster_summary = clusters;
    outputStats{pp}       = stat;
    cluster_masks{pp}     = masks;

    if isempty(clusters)
        continue
    end

    % Add retained clusters to the overall summary.
    if isempty(obs_clusters_sum)
        obs_clusters_sum = clusters;
    else
        obs_clusters_sum = [
            obs_clusters_sum
            clusters
        ];
    end

    % Compute each participant's mean estimate over each cluster's actual
    % channel x time mask.
    n_rows = height(clusters) * n_subjs;

    mean_subject_index      = nan(n_rows, 1);
    mean_subject_id         = strings(n_rows, 1);
    mean_pred               = strings(n_rows, 1);
    mean_clustern           = nan(n_rows, 1);
    mean_fieldtrip_cluster  = nan(n_rows, 1);
    mean_direction          = strings(n_rows, 1);
    mean_prob               = nan(n_rows, 1);
    mean_estimate           = nan(n_rows, 1);

    row_index = 0;

    for cc = 1:height(clusters)

        cluster_mask = masks{cc};

        for ii = 1:n_subjs

            row_index = row_index + 1;

            cluster_values = subjdata{ii}.avg(cluster_mask);

            mean_subject_index(row_index) = ii;
            mean_subject_id(row_index)    = subject_ids(ii);
            mean_pred(row_index)          = string(parameter_name);

            mean_clustern(row_index) = ...
                clusters.clustern(cc);

            mean_fieldtrip_cluster(row_index) = ...
                clusters.fieldtrip_cluster(cc);

            mean_direction(row_index) = ...
                clusters.direction(cc);

            mean_prob(row_index) = ...
                clusters.prob(cc);

            mean_estimate(row_index) = ...
                mean(cluster_values, "omitnan");
        end
    end

    parameter_cluster_means = table( ...
        mean_subject_index, ...
        mean_subject_id, ...
        mean_pred, ...
        mean_clustern, ...
        mean_fieldtrip_cluster, ...
        mean_direction, ...
        mean_prob, ...
        mean_estimate, ...
        'VariableNames', { ...
            'subject_index', ...
            'subject_id', ...
            'pred', ...
            'clustern', ...
            'fieldtrip_cluster', ...
            'direction', ...
            'prob', ...
            'mean_estimate' ...
        } ...
    );

    if isempty(clust_par_means)
        clust_par_means = parameter_cluster_means;
    else
        clust_par_means = [
            clust_par_means
            parameter_cluster_means
        ];
    end
end


%% Assemble model output ==================================================

modelout.obs_clusters_sum = obs_clusters_sum;
modelout.cluster_masks    = cluster_masks;
modelout.fieldtrip_cfg    = fieldtrip_cfg;
modelout.parameter_names  = par_names;
modelout.formula          = string(formula);
modelout.alpha            = fieldtrip_cfg.alpha;
modelout.n_subjects       = n_subjs;
modelout.n_channels       = n_chans;
modelout.n_timepoints     = ts_len;
modelout.channel_labels   = reference_labels;
modelout.time             = reference_time;
modelout.elapsed_seconds  = toc(start_time);

if verbose
    fprintf( ...
        "Done in %.2f seconds. Retained %d clusters.\n", ...
        modelout.elapsed_seconds, ...
        height(obs_clusters_sum) ...
    );
end

end



