
function [cluster_table, cluster_masks] = extract_eeg_clusters( ...
    stat, cluster_field, label_field, direction)
% Extract cluster metadata from a channels x time FieldTrip label matrix.

cluster_table = table();
cluster_masks = cell(0, 1);

cluster_field = char(cluster_field);
label_field   = char(label_field);

if ~isfield(stat, cluster_field) || ...
        isempty(stat.(cluster_field)) || ...
        ~isfield(stat, label_field) || ...
        isempty(stat.(label_field))

    return
end

clusters = stat.(cluster_field);
labelmat = stat.(label_field);

n_channels   = numel(stat.label);
n_timepoints = numel(stat.time);

if numel(labelmat) ~= n_channels * n_timepoints
    error( ...
        ["Unexpected dimensions for %s. Expected %d channel x time " ...
         "points but found %d values."], ...
        label_field, ...
        n_channels * n_timepoints, ...
        numel(labelmat) ...
    );
end

% FieldTrip timelock statistics use chan_time ordering.
labelmat = reshape(labelmat, n_channels, n_timepoints);

n_clusters = numel(clusters);

fieldtrip_cluster = (1:n_clusters)';
direction_column  = repmat(string(direction), n_clusters, 1);

prob        = nan(n_clusters, 1);
clusterstat = nan(n_clusters, 1);

first_sample = nan(n_clusters, 1);
last_sample  = nan(n_clusters, 1);

first_time = nan(n_clusters, 1);
last_time  = nan(n_clusters, 1);
duration   = nan(n_clusters, 1);

n_timepoints_column = nan(n_clusters, 1);
n_channels_column   = nan(n_clusters, 1);
n_points            = nan(n_clusters, 1);

channels = strings(n_clusters, 1);

cluster_masks = cell(n_clusters, 1);

for cl = 1:n_clusters

    cluster_mask = labelmat == cl;
    cluster_masks{cl} = cluster_mask;

    [channel_indices, time_indices] = find(cluster_mask);

    if isempty(time_indices)
        error( ...
            "Cluster %d in %s has no labelled channel-time points.", ...
            cl, ...
            cluster_field ...
        );
    end

    unique_channels = unique(channel_indices);
    unique_times    = unique(time_indices);

    first_sample(cl) = min(unique_times);
    last_sample(cl)  = max(unique_times);

    first_time(cl) = stat.time(first_sample(cl));
    last_time(cl)  = stat.time(last_sample(cl));

    duration(cl) = last_time(cl) - first_time(cl);

    n_timepoints_column(cl) = numel(unique_times);
    n_channels_column(cl)   = numel(unique_channels);
    n_points(cl)            = nnz(cluster_mask);

    channels(cl) = strjoin( ...
        string(stat.label(unique_channels)), ...
        ", " ...
    );

    if isfield(clusters, "prob")
        prob(cl) = clusters(cl).prob;
    end

    if isfield(clusters, "clusterstat")
        clusterstat(cl) = clusters(cl).clusterstat;
    end
end

cluster_table = table( ...
    fieldtrip_cluster, ...
    direction_column, ...
    prob, ...
    clusterstat, ...
    first_sample, ...
    last_sample, ...
    first_time, ...
    last_time, ...
    duration, ...
    n_timepoints_column, ...
    n_channels_column, ...
    n_points, ...
    channels, ...
    'VariableNames', { ...
        'fieldtrip_cluster', ...
        'direction', ...
        'prob', ...
        'clusterstat', ...
        'first_sample', ...
        'last_sample', ...
        'first_time', ...
        'last_time', ...
        'duration', ...
        'n_timepoints', ...
        'n_channels', ...
        'n_points', ...
        'channels' ...
    } ...
);

end

