

function validate_timelock_structure(data, parameter_name, subject_index)
%%% Validate the required fields in one participant's timelock structure.

% ensure that the object is a structure
if ~isstruct(data)
    error( ...
        "Parameter %s, participant %d is not a structure.", ...
        parameter_name, ...
        subject_index ...
    );
end

% ensure that the required fields are present
required_fields = [
    "avg"
    "label"
    "time"
];

for ff = 1:numel(required_fields)

    field_name = required_fields(ff);

    if ~isfield(data, field_name)
        error( ...
            ["Parameter %s, participant %d lacks required " ...
             "FieldTrip field %s."], ...
            parameter_name, ...
            subject_index, ...
            field_name ...
        );
    end
end

% ensure that the 'avg' field contains numeric values and has the
% appropriate dimensions
if ~isnumeric(data.avg) || ~ismatrix(data.avg)
    error("Parameter %s, participant %d: avg must be a numeric channels x time matrix.", ...
        parameter_name, ...
        subject_index ...
    );
end

% ensure that the parameter has a label
if isempty(data.label)
    error( ...
        "Parameter %s, participant %d has no channel labels.", ...
        parameter_name, ...
        subject_index ...
    );
end

% ensure that the parameter has a valid time vector
if ~isnumeric(data.time) || isempty(data.time)
    error( ...
        "Parameter %s, participant %d has no valid time vector.", ...
        parameter_name, ...
        subject_index ...
    );
end

end
